openapi: 3.0.0
info:
  title: Expense Tracker API
  description: API for managing and tracking personal expenses.
  version: 1.0.0

servers:
  - url: /api/v1
    description: Development server

tags:
  - name: budgets
    description: Budget operations

paths:
  /budgets:
    $ref: './resources/budgets.yaml'
  /budgets/{budgetId}:
    $ref: './resources/budget.yaml'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []