server:
  forward-headers-strategy: framework
spring:
  application:
    name: expenses-tracker-service
  devtools:
    add-properties: true
  mvc:
    problem details:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/expenses_tracker_db
    username: expenses_usr111
    password: expenses_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
    republish-outstanding-events-on-restart: true

springdoc:
  api-docs:
    enabled: true
    path: /doc/open-api
  swagger-ui:
    enabled: true
    path: /doc/ui

api:
  security:
    token:
      expiration:
        hours: 2
      secret: a-very-strong-and-secure-secret-key

accounts:
  seeder: true
expenses:
  seeder: true
budgets:
  seeder: true

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework: INFO
