name: Verify PR
run-name: ${{ github.ref }} verify PR.

on:
  pull_request:

concurrency:
  group: verify-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      TZ: “Europe/Madrid”

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Setup Maven Cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile and verify
        run: mvn -B clean verify

      - name: Sonar Cloud Scan
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=jalucenyo_expense-tracker-service -Dsonar.organization=jalucenyo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}